"use client";
import { useState } from "react";
import { signOut } from "next-auth/react";
import {
  BarChart, Bar, PieChart, Pie, Cell,
  XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, Legend,
} from "recharts";
import Link from "next/link";

const PIE_COLORS = ["#22c55e", "#4ade80", "#86efac", "#16a34a", "#166534"];

interface CorporateClientProps {
  user: { name: string; email: string };
  stats: { totalUsers: number; totalGreenPurchases: number; totalTokens: number; carbonSaved: number };
  monthlyData: { month: string; purchases: number; tokens: number }[];
  categoryData: { name: string; value: number }[];
}

export function CorporateClient({ user, stats, monthlyData, categoryData }: CorporateClientProps) {
  const [generating, setGenerating] = useState(false);

  async function downloadReport() {
    setGenerating(true);
    const { default: jsPDF } = await import("jspdf");
    const { default: autoTable } = await import("jspdf-autotable");

    const doc = new jsPDF();
    const now = new Date();

    doc.setFillColor(5, 10, 6);
    doc.rect(0, 0, 210, 297, "F");
    doc.setTextColor(34, 197, 94);
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.text("GreenLens ESG Report", 20, 30);

    doc.setTextColor(134, 239, 172);
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.text(`Company: ${user.name}`, 20, 45);
    doc.text(`Report Date: ${now.toLocaleDateString("en-IN")}`, 20, 55);
    doc.text(`Generated: ${now.toLocaleString("en-IN")}`, 20, 65);

    doc.setDrawColor(34, 197, 94);
    doc.setLineWidth(0.5);
    doc.line(20, 72, 190, 72);

    doc.setTextColor(34, 197, 94);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("Key Sustainability Metrics", 20, 85);

    autoTable(doc, {
      startY: 92,
      head: [["Metric", "Value"]],
      body: [
        ["Total Green Shoppers", stats.totalUsers.toLocaleString()],
        ["Total Sustainable Purchases", stats.totalGreenPurchases.toLocaleString()],
        ["Green Tokens Distributed to Users", stats.totalTokens.toLocaleString()],
        ["Estimated Carbon Saved (kg CO₂)", stats.carbonSaved.toFixed(2)],
        ["Monetary Value Returned to Users (₹)", (stats.totalTokens * 0.1).toFixed(2)],
      ],
      styles: { fillColor: [14, 30, 20], textColor: [134, 239, 172], fontSize: 10 },
      headStyles: { fillColor: [22, 101, 52], textColor: [134, 239, 172] },
      alternateRowStyles: { fillColor: [10, 20, 16] },
    });

    if (categoryData.length > 0) {
      const afterTable = (doc as any).lastAutoTable.finalY + 15;
      doc.setTextColor(34, 197, 94);
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("Category Breakdown", 20, afterTable);

      autoTable(doc, {
        startY: afterTable + 7,
        head: [["Category", "Purchases"]],
        body: categoryData.map(c => [c.name, c.value]),
        styles: { fillColor: [14, 30, 20], textColor: [134, 239, 172], fontSize: 10 },
        headStyles: { fillColor: [22, 101, 52], textColor: [134, 239, 172] },
        alternateRowStyles: { fillColor: [10, 20, 16] },
      });
    }

    doc.setTextColor(30, 58, 43);
    doc.setFontSize(8);
    doc.text("This report contains anonymized aggregate data. Individual user data is not disclosed.", 20, 285);
    doc.text("Generated by GreenLens Platform · greenlens.app", 20, 291);

    doc.save(`GreenLens_ESG_Report_${now.toISOString().split("T")[0]}.pdf`);
    setGenerating(false);
  }

  return (
    <div className="min-h-screen bg-surface-900">
      {/* Sidebar */}
      <aside className="fixed top-0 left-0 h-full w-60 border-r border-brand-900/40 bg-surface-800/50 backdrop-blur-xl flex flex-col z-40">
        <div className="p-6 border-b border-brand-900/40">
          <Link href="/" className="flex items-center gap-2">
            <span className="text-2xl">🌿</span>
            <span className="font-display font-bold text-brand-300">GreenLens</span>
          </Link>
          <div className="mt-3 inline-flex items-center gap-1.5 bg-brand-900/40 border border-brand-700/30 rounded-full px-3 py-1">
            <span className="w-1.5 h-1.5 bg-brand-400 rounded-full" />
            <span className="text-brand-500 text-xs font-mono">Corporate</span>
          </div>
        </div>

        <nav className="flex-1 p-4 space-y-1">
          <div className="px-4 py-2.5 bg-brand-500/15 text-brand-300 border border-brand-500/30 rounded-lg text-sm font-medium">
            <span className="font-mono text-xs mr-2">◎</span> ESG Dashboard
          </div>
        </nav>

        <div className="p-4 border-t border-brand-900/40">
          <div className="mb-3 px-3">
            <p className="text-brand-300 text-sm font-medium truncate">{user.name}</p>
            <p className="text-brand-700 text-xs font-mono truncate">{user.email}</p>
          </div>
          <button
            onClick={() => signOut({ callbackUrl: "/" })}
            className="w-full text-left px-3 py-2 text-brand-700 text-xs hover:text-red-400 transition-colors font-mono"
          >
            → Sign out
          </button>
        </div>
      </aside>

      {/* Main */}
      <main className="ml-60 p-8">
        <div className="mb-8 flex items-center justify-between">
          <div>
            <h1 className="font-display text-3xl font-bold text-brand-100">ESG Analytics</h1>
            <p className="text-brand-600 text-sm mt-1 font-mono">Anonymized aggregate sustainability data</p>
          </div>
          <button
            onClick={downloadReport}
            disabled={generating}
            className="gl-btn-primary py-3 px-6 flex items-center gap-2"
          >
            <span>{generating ? "⏳" : "📄"}</span>
            {generating ? "Generating…" : "Download ESG Report"}
          </button>
        </div>

        {/* ── Token wallet — grayed out, corporate accounts don't earn tokens ── */}
        <div className="glow-card rounded-2xl p-5 mb-6 opacity-50 pointer-events-none select-none relative overflow-hidden">
          {/* Lock overlay badge */}
          <div className="absolute top-3 right-4 flex items-center gap-1.5 bg-surface-600 border border-brand-900/60 rounded-full px-3 py-1">
            <span className="text-xs">🔒</span>
            <span className="text-brand-700 text-xs font-mono">User accounts only</span>
          </div>
          <p className="text-brand-600 text-xs font-mono uppercase tracking-widest mb-3">Token Wallet</p>
          <div className="flex items-end gap-6">
            <div>
              <p className="font-display text-4xl font-black text-brand-300">—</p>
              <p className="text-brand-700 text-xs mt-1">Token Balance</p>
            </div>
            <div>
              <p className="font-display text-4xl font-black text-brand-400">—</p>
              <p className="text-brand-700 text-xs mt-1">₹ Equivalent</p>
            </div>
          </div>
          <p className="text-brand-800 text-xs font-mono mt-3">
            Green Tokens are earned by individual users on eco purchases. Corporate accounts track ESG metrics only.
          </p>
        </div>

        {/* ESG Stats */}
        <div className="grid grid-cols-4 gap-4 mb-6">
          {[
            { label: "Green Shoppers",    value: stats.totalUsers.toLocaleString(),           icon: "👥", color: "brand-300" },
            { label: "Eco Purchases",     value: stats.totalGreenPurchases.toLocaleString(),  icon: "🛒", color: "brand-400" },
            { label: "Tokens to Users",   value: stats.totalTokens.toLocaleString(),          icon: "🪙", color: "brand-500" },
            { label: "Carbon Saved (kg)", value: stats.carbonSaved.toFixed(1),                icon: "🌍", color: "brand-400" },
          ].map(s => (
            <div key={s.label} className="glow-card rounded-2xl p-5">
              <div className="flex items-center gap-2 mb-3">
                <span className="text-xl">{s.icon}</span>
                <p className="text-brand-600 text-xs font-mono uppercase tracking-widest">{s.label}</p>
              </div>
              <p className={`font-display text-3xl font-black text-${s.color}`}>{s.value}</p>
            </div>
          ))}
        </div>

        {/* Monetary return to users */}
        <div className="glow-card rounded-xl p-4 mb-6 flex items-center gap-4 border-brand-500/20">
          <span className="text-2xl">💰</span>
          <div>
            <p className="text-brand-300 font-medium text-sm">Total Monetary Value Returned to Users</p>
            <p className="font-display text-2xl font-bold text-brand-400">
              ₹{(stats.totalTokens * 0.1).toFixed(2)}
            </p>
          </div>
          <div className="ml-auto text-brand-700 text-xs font-mono">@ ₹0.10 per token</div>
        </div>

        {/* Charts */}
        <div className="grid grid-cols-2 gap-4 mb-6">
          <div className="glow-card rounded-2xl p-6">
            <p className="text-brand-400 text-sm font-medium mb-4">Monthly Green Purchases</p>
            {monthlyData.some(m => m.purchases > 0) ? (
              <ResponsiveContainer width="100%" height={200}>
                <BarChart data={monthlyData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="month" />
                  <YAxis />
                  <Tooltip
                    contentStyle={{ background: "#0f1e17", border: "1px solid #166534", borderRadius: 8, fontSize: 12 }}
                  />
                  <Legend />
                  <Bar dataKey="purchases" name="Purchases" fill="#22c55e" radius={[4, 4, 0, 0]} />
                  <Bar dataKey="tokens"    name="Tokens"    fill="#4ade80" radius={[4, 4, 0, 0]} />
                </BarChart>
              </ResponsiveContainer>
            ) : (
              <div className="h-48 flex items-center justify-center text-brand-700 text-sm font-mono">
                No purchase data yet
              </div>
            )}
          </div>

          <div className="glow-card rounded-2xl p-6">
            <p className="text-brand-400 text-sm font-medium mb-4">Eco Category Distribution</p>
            {categoryData.length > 0 ? (
              <ResponsiveContainer width="100%" height={200}>
                <PieChart>
                  <Pie data={categoryData} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={80}>
                    {categoryData.map((_, index) => (
                      <Cell key={index} fill={PIE_COLORS[index % PIE_COLORS.length]} />
                    ))}
                  </Pie>
                  <Tooltip
                    contentStyle={{ background: "#0f1e17", border: "1px solid #166534", borderRadius: 8, fontSize: 12 }}
                  />
                  <Legend />
                </PieChart>
              </ResponsiveContainer>
            ) : (
              <div className="h-48 flex items-center justify-center text-brand-700 text-sm font-mono">
                No category data yet
              </div>
            )}
          </div>
        </div>

        {/* Privacy notice */}
        <div className="bg-surface-700/30 border border-brand-900/40 rounded-xl p-4 flex items-start gap-3">
          <span className="text-brand-500 text-lg shrink-0">🔒</span>
          <p className="text-brand-600 text-xs font-mono leading-relaxed">
            All data shown is anonymized and aggregated. No individual user information is disclosed.
            This dashboard complies with data privacy regulations and GDPR standards.
          </p>
        </div>
      </main>
    </div>
  );
}